// Code generated by protoc-gen-go.
// source: menu.proto
// DO NOT EDIT!

package menu

//import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
//var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type MenuSt struct {
	Button           []*ButtonSt `protobuf:"bytes,1,rep,name=button" json:"button,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MenuSt) Reset()         { *m = MenuSt{} }
func (m *MenuSt) String() string { return proto.CompactTextString(m) }
func (*MenuSt) ProtoMessage()    {}

func (m *MenuSt) GetButton() []*ButtonSt {
	if m != nil {
		return m.Button
	}
	return nil
}

type ButtonSt struct {
	Type             *string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Key              *string  `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Url              *string  `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	SubButton        []string `protobuf:"bytes,5,rep,name=sub_button" json:"sub_button,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ButtonSt) Reset()         { *m = ButtonSt{} }
func (m *ButtonSt) String() string { return proto.CompactTextString(m) }
func (*ButtonSt) ProtoMessage()    {}

func (m *ButtonSt) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ButtonSt) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ButtonSt) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ButtonSt) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *ButtonSt) GetSubButton() []string {
	if m != nil {
		return m.SubButton
	}
	return nil
}

type ErrorSt struct {
	Errcode          *int32  `protobuf:"varint,1,req,name=errcode" json:"errcode,omitempty"`
	Errmsg           *string `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ErrorSt) Reset()         { *m = ErrorSt{} }
func (m *ErrorSt) String() string { return proto.CompactTextString(m) }
func (*ErrorSt) ProtoMessage()    {}

func (m *ErrorSt) GetErrcode() int32 {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return 0
}

func (m *ErrorSt) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

func init() {
}
